- id: terraform-fmt
  name: Format Terraform configuration files
  description: Rewrites Terraform `.tf` and `.tfvars` files to a canonical format
  entry: terraform fmt -list=true -write=true -recursive
  language: system
  files: (\.tf|\.tfvars)$
  pass_filenames: false
